language: node_js
node_js:
  - "4.2"
  - "stable"
script:
  - npm run lint
  - npm test
  - travis_retry node examples/advanced.js
  - travis_retry node examples/simple.js
  - travis_retry npm link && npm link crawlkit --silent && node examples/tonic.js
