language: node_js
node_js:
  - "4.2"
  - "stable"
script:
  - npm run lint
  - npm test
  - npm link --silent && npm link crawlkit --silent
  - travis_retry node examples/advanced.js
  - travis_retry node examples/simple.js
  - travis_retry node examples/tonic.js
